In [2]:
import relpy as pm
import numpy as np
import scipy.sparse as sp

In [3]:
params = pm.Params()
params.ufact

1.01

In [4]:
Q=np.array([[-5,2,3],[2,-3,1],[1,1,-2]], dtype='float')

In [5]:
Q

array([[-5.,  2.,  3.],
       [ 2., -3.,  1.],
       [ 1.,  1., -2.]])

In [6]:
pis = pm.ctmc_st_gth_dense(Q)

In [7]:
pm.ctmc_st_gs_dense(Q, np.array([1,1,1]), params)

array([0.2173913 , 0.30434783, 0.47826087])

In [8]:
params.iter

30

In [9]:
dQ=np.array([[-1,1,0],[0,0,0],[0,0,0]])

In [10]:
dpis = pm.ctmc_stsen_gs_dense(Q, np.array([1,1,1]), np.dot(pis, dQ), pis, params)

In [11]:
pis @ Q

array([-5.55111512e-17,  5.55111512e-17, -1.11022302e-16])

In [12]:
Q @ pis

array([ 0.95652174,  0.        , -0.43478261])

In [13]:
dpis @ Q + pis @ dQ

array([-5.55111512e-17,  0.00000000e+00, -6.93889390e-18])

In [14]:
sum(dpis)

0.0

In [15]:
dpis

array([-0.02835539,  0.04725898, -0.01890359])

In [16]:
params.rmax = 1000

In [17]:
x0=np.array([[1,0,0],[0,0,1]]).transpose()
x0

array([[1, 0],
       [0, 0],
       [0, 1]])

In [18]:
pm.ctmc_mexp_dense(Q, x0, 1, True, params)

array([[0.21885603, 0.21339907],
       [0.30429041, 0.29507088],
       [0.47685357, 0.49153005]])

In [19]:
cx0=np.zeros_like(x0)
cx0

array([[0, 0],
       [0, 0],
       [0, 0]])

In [20]:
pm.ctmc_mexpint_dense(Q, x0, cx0, 10, True, params)

(array([[0.2173913 , 0.2173913 ],
        [0.30434783, 0.30434783],
        [0.47826087, 0.47826087]]), array([[2.29678639, 2.12287334],
        [2.99810964, 2.95463138],
        [4.70510397, 4.92249527]]))

In [21]:
spQ=sp.csc_matrix(Q)
print(Q)
print(spQ)

[[-5.  2.  3.]
 [ 2. -3.  1.]
 [ 1.  1. -2.]]
  (0, 0)	-5.0
  (1, 0)	2.0
  (2, 0)	1.0
  (0, 1)	2.0
  (1, 1)	-3.0
  (2, 1)	1.0
  (0, 2)	3.0
  (1, 2)	1.0
  (2, 2)	-2.0


In [22]:
print(spQ)

  (0, 0)	-5.0
  (1, 0)	2.0
  (2, 0)	1.0
  (0, 1)	2.0
  (1, 1)	-3.0
  (2, 1)	1.0
  (0, 2)	3.0
  (1, 2)	1.0
  (2, 2)	-2.0


In [23]:
pm.ctmc_st_gth_sparse(Q=spQ)

array([0.2173913 , 0.30434783, 0.47826087])

In [24]:
pis

array([0.2173913 , 0.30434783, 0.47826087])

In [25]:
pm.ctmc_mexp_sparse(spQ, x0, 1, True, params)

array([[0.21885603, 0.21339907],
       [0.30429041, 0.29507088],
       [0.47685357, 0.49153005]])

In [26]:
dpis = pm.ctmc_stsen_gs_sparse(spQ, np.array([1,1,1]), np.dot(pis, dQ), pis, params)

In [27]:
dpis

array([-0.02835539,  0.04725898, -0.01890359])

In [28]:
spQ.todense()

matrix([[-5.,  2.,  3.],
        [ 2., -3.,  1.],
        [ 1.,  1., -2.]])

In [29]:
Q.shape[0]

3

In [30]:
np.full(10,1/10)

array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1])

In [31]:
np.dot(np.array([1,2,3]), np.array([4,5,6]))

32