In [1]:
import relpy as pm
import numpy as np
import scipy.sparse as sp

In [2]:
params = pm.Params()
params.ufact

1.01

In [3]:
Q=np.array([[-5,2,3],[2,-3,1],[1,1,-2]], dtype='float')

In [4]:
Q

array([[-5.,  2.,  3.],
       [ 2., -3.,  1.],
       [ 1.,  1., -2.]])

In [5]:
pis = pm.ctmc_st_gth_dense(Q)

In [6]:
pm.ctmc_st_gs_dense(Q, np.array([1,1,1]), params)

array([0.2173913 , 0.30434783, 0.47826087])

In [7]:
params.iter

30

In [8]:
dQ=np.array([[-1,1,0],[0,0,0],[0,0,0]])

In [9]:
dpis = pm.ctmc_stsen_gs_dense(Q, np.array([1,1,1]), np.dot(pis, dQ), pis, params)

In [10]:
pis @ Q

array([-5.55111512e-17,  5.55111512e-17, -1.11022302e-16])

In [11]:
Q @ pis

array([ 0.95652174,  0.        , -0.43478261])

In [12]:
dpis @ Q + pis @ dQ

array([-5.55111512e-17,  0.00000000e+00, -6.93889390e-18])

In [13]:
sum(dpis)

0.0

In [14]:
dpis

array([-0.02835539,  0.04725898, -0.01890359])

In [15]:
params.rmax = 1000

In [16]:
x0=np.array([[1,0,0],[0,0,1]]).transpose()
x0

array([[1, 0],
       [0, 0],
       [0, 1]])

In [17]:
pm.ctmc_mexp_dense(Q, x0, 1, True, params)

array([[0.21885603, 0.21339907],
       [0.30429041, 0.29507088],
       [0.47685357, 0.49153005]])

In [18]:
cx0=np.zeros_like(x0)
cx0

array([[0, 0],
       [0, 0],
       [0, 0]])

In [19]:
pm.ctmc_mexpint_dense(Q, x0, cx0, 10, True, params)

(array([[0.2173913 , 0.2173913 ],
        [0.30434783, 0.30434783],
        [0.47826087, 0.47826087]]), array([[2.29678639, 2.12287334],
        [2.99810964, 2.95463138],
        [4.70510397, 4.92249527]]))

In [20]:
spQ=sp.csc_matrix(Q)
print(Q)
print(spQ)

[[-5.  2.  3.]
 [ 2. -3.  1.]
 [ 1.  1. -2.]]
  (0, 0)	-5.0
  (1, 0)	2.0
  (2, 0)	1.0
  (0, 1)	2.0
  (1, 1)	-3.0
  (2, 1)	1.0
  (0, 2)	3.0
  (1, 2)	1.0
  (2, 2)	-2.0


In [21]:
print(spQ)

  (0, 0)	-5.0
  (1, 0)	2.0
  (2, 0)	1.0
  (0, 1)	2.0
  (1, 1)	-3.0
  (2, 1)	1.0
  (0, 2)	3.0
  (1, 2)	1.0
  (2, 2)	-2.0


In [22]:
pm.ctmc_st_gth_sparse(Q=spQ)

array([0.2173913 , 0.30434783, 0.47826087])

In [23]:
pis

array([0.2173913 , 0.30434783, 0.47826087])

In [24]:
pm.ctmc_mexp_sparse(spQ, x0, 1, True, params)

array([[0.21885603, 0.21339907],
       [0.30429041, 0.29507088],
       [0.47685357, 0.49153005]])

In [25]:
dpis = pm.ctmc_stsen_gs_sparse(spQ, np.array([1,1,1]), np.dot(pis, dQ), pis, params)

In [26]:
dpis

array([-0.02835539,  0.04725898, -0.01890359])

In [27]:
spQ.todense()

matrix([[-5.,  2.,  3.],
        [ 2., -3.,  1.],
        [ 1.,  1., -2.]])

In [28]:
Q.shape[0]

3

In [29]:
np.full(10,1/10)

array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1])

In [30]:
np.dot(np.array([1,2,3]), np.array([4,5,6]))

32

In [31]:
t=np.array([1,1,1,1,1], dtype='float')

In [32]:
res=pm.ctmc_tran_sparse(spQ, x0, cx0, t, True, params)
res[0]

array([0.21885603, 0.30429041, 0.47685357, 0.21339907, 0.29507088,
       0.49153005, 0.21739877, 0.30435996, 0.47824127, 0.21728399,
       0.30408934, 0.47862667, 0.21739146, 0.30434818, 0.47826036,
       0.21738834, 0.30434066, 0.478271  , 0.21739131, 0.30434784,
       0.47826086, 0.21739122, 0.30434763, 0.47826115, 0.2173913 ,
       0.30434783, 0.47826087, 0.2173913 , 0.30434782, 0.47826088])

In [33]:
res[0].reshape((5, 2, 3), order='F')

array([[[0.21885603, 0.30408934, 0.47826086],
        [0.49153005, 0.21738834, 0.30434783]],

       [[0.30429041, 0.47862667, 0.21739122],
        [0.21739877, 0.30434066, 0.47826087]],

       [[0.47685357, 0.21739146, 0.30434763],
        [0.30435996, 0.478271  , 0.2173913 ]],

       [[0.21339907, 0.30434818, 0.47826115],
        [0.47824127, 0.21739131, 0.30434782]],

       [[0.29507088, 0.47826036, 0.2173913 ],
        [0.21728399, 0.30434784, 0.47826088]]])

In [34]:
pm.ctmc_mexp_dense(Q, x0, 1, True, params)

array([[0.21885603, 0.21339907],
       [0.30429041, 0.29507088],
       [0.47685357, 0.49153005]])

In [35]:
cx0

array([[0, 0],
       [0, 0],
       [0, 0]])

In [37]:
rwd = np.array([[1,1,0],[0,1,1]]).transpose()
res=pm.ctmc_tran_rwd_dense(Q, x0, cx0, rwd, t, True, params)
res

(array([[0.2173913 , 0.2173913 ],
        [0.30434783, 0.30434782],
        [0.47826087, 0.47826088]]), array([[1.20982987, 1.03591682],
        [1.47637051, 1.43289225],
        [2.31379962, 2.53119092]]), array([0.52314643, 0.78114397, 0.50846995, 0.78660093, 0.52175873,
        0.78260123, 0.52137333, 0.78271601, 0.52173964, 0.78260854,
        0.521729  , 0.78261166, 0.52173914, 0.78260869, 0.52173885,
        0.78260878, 0.52173913, 0.7826087 , 0.52173912, 0.7826087 ]), array([0.59894291, 0.65998759, 0.38554385, 0.83255075, 1.12097767,
        1.44234587, 0.90369368, 1.61622719, 1.64272197, 2.22495278,
        1.42533364, 2.39886496, 2.16446124, 3.00756144, 1.94707002,
        3.18147446, 2.68620038, 3.79017013, 2.46880908, 3.96408318]))